#!/usr/bin/env ruby

class Archiver
  def self.archive_done(lines)
    groups = lines.reduce({ active: [], done: [] }) do |m, line|
      (line.match(/\@done/) ? m[:done] : m[:active]) << line unless line.match(/Archive:/)
      m
    end
    (groups[:active] << "Archive:\n" << groups[:done]).join
  end
end

if $0 == __FILE__
  puts Archiver.archive_done($stdin.readlines)
end
