#!/usr/bin/env ruby
class Text
  def self.delimited(left, right, text)
    text.scan(/w+/).filter do |token| 
      token == left || token == right 
    end.reduce([]) do |stack, token|
      # left with no closing right: stack non-empty when reduce returns
      # right with no matching left: stack empty when right encountered
      if token == left
        stack.push token 
      elsif token == right and stack.peek == left
        stack.pop 
      else # error case?
      end
    end
  end
end

if __file__ == $1
  puts Text.delimited(ARGV[0], ARGV[1], $stdin.read.chomp)
end
